object Form1: TForm1
  Color = clWhite
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = 0
  Font.Name = 'Arial'
  Font.Size = 8
  Font.Style = []
  FormContainer = 'body'
  FormStyle = fsNormal
  Height = 697
  Left = 0
  OnCreate = WebFormCreate
  OnShow = WebFormShow
  ParentFont = False
  TabOrder = 0
  Top = 0
  Width = 951
  object WebLabel2: TWebLabel
    Caption = 'Voornaam :'
    ChildOrder = 0
    DragMode = dmManual
    ElementID = 'firstName'
    ElementPosition = epRelative
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = 0
    Font.Name = 'Arial'
    Font.Size = 8
    Font.Style = []
    Height = 45
    Left = 400
    ParentFont = False
    TextDirection = tdDefault
    Top = 217
    Width = 206
  end
  object WebLabel3: TWebLabel
    Caption = 'Naam : '
    ChildOrder = 0
    DragMode = dmManual
    ElementID = 'lastName'
    ElementPosition = epRelative
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = 0
    Font.Name = 'Arial'
    Font.Size = 8
    Font.Style = []
    Height = 45
    Left = 400
    ParentFont = False
    TextDirection = tdDefault
    Top = 257
    Width = 206
  end
  object txtFirstname: TWebEdit
    Alignment = taLeftJustify
    AutoFocus = False
    AutoSelect = False
    AutoSize = False
    ChildOrder = 1
    Color = clWindow
    DragMode = dmManual
    EditType = weString
    ElementClassName = 'form-control'
    ElementID = 'inputFirstName'
    ElementPosition = epRelative
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = 0
    Font.Name = 'Arial'
    Font.Size = 8
    Font.Style = []
    Height = 22
    HideSelection = False
    Left = 480
    MaxLength = 0
    ParentFont = False
    Required = False
    ShowFocus = True
    TabOrder = 0
    TextDirection = tdDefault
    Top = 214
    Width = 121
  end
  object WebButton1: TWebButton
    Caption = 'Start the game'
    ChildOrder = 3
    Color = clNone
    Default = False
    DragMode = dmManual
    ElementClassName = 'btn btn-success'
    ElementID = 'btnLogin'
    ElementPosition = epRelative
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = 0
    Font.Name = 'Arial'
    Font.Size = 8
    Font.Style = []
    Height = 21
    HeightStyle = ssAuto
    Left = 400
    OnClick = WebButton1Click
    ParentFont = False
    Role = 'button'
    TabOrder = 0
    TextDirection = tdDefault
    Top = 312
    Width = 201
  end
  object txtLastname: TWebEdit
    Alignment = taLeftJustify
    AutoFocus = False
    AutoSelect = False
    AutoSize = False
    ChildOrder = 6
    Color = clWindow
    DragMode = dmManual
    EditType = weString
    ElementClassName = 'form-control'
    ElementID = 'inputLastName'
    ElementPosition = epRelative
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = 0
    Font.Name = 'Arial'
    Font.Size = 8
    Font.Style = []
    Height = 22
    HideSelection = False
    Left = 480
    MaxLength = 0
    ParentFont = False
    Required = False
    ShowFocus = True
    TabOrder = 0
    TextDirection = tdDefault
    Top = 254
    Width = 121
  end
  object IndexedDBClientDataSet: TWebIndexedDbClientDataset
    IDBAutoIncrement = True
    IDBDatabaseName = 'scoreDB'
    IDBKeyFieldName = 'id'
    IDBObjectStoreName = 'highScoreList'
    Params = <>
    Left = 360
    Top = 560
  end
  object WebDataSource1: TWebDataSource
    DataSet = IndexedDBClientDataSet
    Left = 232
    Top = 560
  end
end
